console.log(7 > 5); //true
console.log(7 < 5); //false
console.log(7 < "5"); //false
console.log(7 !== 7); //false
console.log(7 !== "7"); //true
console.log(7 != 5); //true
console.log(7 == 7); //true
console.log(7 === "7"); //false
console.log(7 >= 5); //true
